// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChEGqfe3PXbXMOlb7W8zo3b_ZxrRTzIgo',
    appId: '1:412158470802:web:786eae1322f73f4b7a144b',
    messagingSenderId: '412158470802',
    projectId: 'flutter-demo-244d6',
    authDomain: 'flutter-demo-244d6.firebaseapp.com',
    storageBucket: 'flutter-demo-244d6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABG0pwfNaXLQpZv9Qx9R7FySRsaFvWvj8',
    appId: '1:412158470802:android:85200f1e469df0797a144b',
    messagingSenderId: '412158470802',
    projectId: 'flutter-demo-244d6',
    storageBucket: 'flutter-demo-244d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCEpBZVX5GcJC1utYeCLpfiQxeCX7bNdk',
    appId: '1:412158470802:ios:f13d2849ee8a39157a144b',
    messagingSenderId: '412158470802',
    projectId: 'flutter-demo-244d6',
    storageBucket: 'flutter-demo-244d6.appspot.com',
    iosBundleId: 'com.example.flutterDemoProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCEpBZVX5GcJC1utYeCLpfiQxeCX7bNdk',
    appId: '1:412158470802:ios:f13d2849ee8a39157a144b',
    messagingSenderId: '412158470802',
    projectId: 'flutter-demo-244d6',
    storageBucket: 'flutter-demo-244d6.appspot.com',
    iosBundleId: 'com.example.flutterDemoProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChEGqfe3PXbXMOlb7W8zo3b_ZxrRTzIgo',
    appId: '1:412158470802:web:84795a6f7ef673e17a144b',
    messagingSenderId: '412158470802',
    projectId: 'flutter-demo-244d6',
    authDomain: 'flutter-demo-244d6.firebaseapp.com',
    storageBucket: 'flutter-demo-244d6.appspot.com',
  );
}
